#include <stdio.h>

/* Function to calculate (base^power) % mod */
long long powerMod(long long base, long long power, long long mod)
{
    long long result = 1;
    int i;

    for(i = 0; i < power; i++)
    {
        result = (result * base) % mod;
    }

    return result;
}

int main()
{
    long long p, g;
    long long privateA, privateB;
    long long publicA, publicB;
    long long secretA, secretB;

    printf("Enter prime number (p): ");
    scanf("%lld", &p);

    printf("Enter primitive root (g): ");
    scanf("%lld", &g);

    printf("Enter private key of Alice: ");
    scanf("%lld", &privateA);

    printf("Enter private key of Bob: ");
    scanf("%lld", &privateB);

    /* Generate public keys */
    publicA = powerMod(g, privateA, p);
    publicB = powerMod(g, privateB, p);

    /* Generate shared secret */
    secretA = powerMod(publicB, privateA, p);
    secretB = powerMod(publicA, privateB, p);

    printf("\n----- DIFFIE-HELLMAN KEY EXCHANGE -----\n");

    printf("\nPublic Parameters:\n");
    printf("Prime p       : %lld\n", p);
    printf("Primitive g   : %lld\n", g);

    printf("\nAlice:\n");
    printf("Private Key   : %lld\n", privateA);
    printf("Public Key    : %lld\n", publicA);

    printf("\nBob:\n");
    printf("Private Key   : %lld\n", privateB);
    printf("Public Key    : %lld\n", publicB);

    printf("\nShared Secret generated by Alice: %lld\n", secretA);
    printf("Shared Secret generated by Bob  : %lld\n", secretB);

    if(secretA == secretB)
        printf("\nKey Exchange Successful!\n");
    else
        printf("\nKey Exchange Failed!\n");

    return 0;
}
